settings:
  facebook_url:
    value: http://facebook.com/matthew.beale
    description: 
  github_url:
    value: https://github.com/mixonic
    description: 
  google_plus_url:
    value: 
    description: 
  instagram_url:
    value: 
    description: 
  linkedin_url:
    value: http://www.linkedin.com/in/matthewbeale
    description: 
  tumblr_url:
    value: 
    description: 
  twitter_url:
    value: http://twitter.com/mixonic
    description: 
  youtube_url:
    value: 
    description: 
title: Matthew Beale
