settings:
  facebook_url:
    value: 'http://facebook.com/matthew.beale'
    description:  
  gitHub_url:
    value: 'http://facebook.com/matthew.beale'
    description:  
  google_plus_url:
    value: 'http://facebook.com/matthew.beale'
    description:  
  instagram_url:
    value: 'http://facebook.com/matthew.beale'
    description:  
  linkedIn_url:
    value: 'http://facebook.com/matthew.beale'
    description:  
  tumblr_url:
    value: 'http://facebook.com/matthew.beale'
    description:  
  twitter_url:
    value: 'http://facebook.com/matthew.beale'
    description:  
  youtube_url:
    value: 'http://facebook.com/matthew.beale'
    description:  
